version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es-ml-lab
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=changeme
      - indices.memory.index_buffer_size=20%
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana-ml-lab
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=OZZCxSVB4SDf5gkT2PGz
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  seeder:
    image: alpine:3.20
    container_name: seeder-ml-lab
    # monta o diretório local dentro do container
    volumes:
      - ./:/work
    working_dir: /work
    # instala curl/bash/grep e roda o script bulk dentro do container (sem Git Bash do host)
    command: >
      sh -lc "
        apk add --no-cache curl bash grep coreutils >/dev/null &&
        chmod +x /work/data-generator-bulk.sh &&
        /work/data-generator-bulk.sh
      "
    depends_on:
      - elasticsearch
